# Change these first
owner: Smithsonian # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: ChrisMoriarty

sites:
  - name: MPC Homepage
    url: https://www.minorplanetcenter.net
  - name: NEOCP
    url: https://minorplanetcenter.net/iau/NEO/toconfirm_tabular.html
  - name: Data Subdomain
    url: https://data.minorplanetcenter.net/
  - name: Public VM Test
    url: https://mpc-vm10.cfa.harvard.edu
    __dangerous__disable_verify_peer: true
  - name: Designation Identifier API
    method: GET
    url: "https://data.minorplanetcenter.net/api/query-identifier"
    headers:
      - "Content-Type: application/text"
    body: "Ceres"
  - name: Website Server
    check: "tcp-ping"
    url: mpcweb2.si.edu
    port: 80
  - name: Data Subdomain Server
    check: "tcp-ping"
    url: mpcweb6.cfa.harvard.edu

assignees: # Users to assign downtime issues (optional)
  - ChrisMoriarty

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MPC Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
