# Change these first
owner: Smithsonian # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: ChrisMoriarty

sites:
  - name: MPC Homepage
    url: https://www.minorplanetcenter.net
  - name: NEOCP
    url: https://minorplanetcenter.net/iau/NEO/toconfirm_tabular.html
  - name: Data Subdomain
    url: https://data.minorplanetcenter.net/
  - name: Public VM Test
    url: https://mpc-vm10.cfa.harvard.edu
    __dangerous__disable_verify_peer: true
  - name: Designation Identifier API
    method: GET
    url: https://data.minorplanetcenter.net/api/query-identifier
    headers:
      - "Content-Type: application/text"
    body: "Ceres"
  - name: Data Subdomain Server
    check: "tcp-ping"
    url: mpcweb6.cfa.harvard.edu

assignees: # Users to assign downtime issues (optional)
  - ChrisMoriarty

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://www.iau.org/static/archives/images/large/mpc-logo.jpg
  name: MPC Status
  introTitle: "Experimental prototype for automated real-time status for MPC servers and services"
  introMessage: "Users can follow issues automatically created in Github when downtime occurs"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: MPC Homepage
      href: https://minorplanetcenter.net
    - title: MPC Helpdesk
      href: https://mpc-service.atlassian.net/servicedesk/customer/portals

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
