# Change these first
owner: Smithsonian # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: ChrisMoriarty

sites:
  - name: NEOCP
    url: https://minorplanetcenter.net/iau/NEO/toconfirm_tabular.html
    maxResponseTime: 20000
  - name: MPC Homepage
    url: https://www.minorplanetcenter.net
    maxResponseTime: 20000
  - name: MPC Data Services Homepage
    url: https://data.minorplanetcenter.net/
    maxResponseTime: 20000
  - name: MPC Explorer
    url: https://data.minorplanetcenter.net/explorer/
    maxResponseTime: 20000
  - name: Designation Identifier
    method: GET
    url: https://data.minorplanetcenter.net/api/query-identifier
    headers:
      - "Content-Type: application/text"
    body: "Ceres"
    maxResponseTime: 20000
    
#  - name: Public VM Test
#    url: https://mpc-vm10.cfa.harvard.edu
#    __dangerous__disable_verify_peer: true
#
#  - name: (PING) MPC Data Services Server
#    check: "tcp-ping"
#    url: mpcweb6.cfa.harvard.edu

# assignees: # Users to assign downtime issues (optional)
#   - ChrisMoriarty

# Add 1s delay in between each check to give apache a better chance at replying. 
delay: 1000

skipDeleteIssues: false # Skip deleting the downtime issues after recovery

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.minorplanetcenter.net
  theme: ocean
#  baseUrl: /upptime
  logoUrl: https://https://smithsonian.github.io/upptime/assets/mpc_logo.png
  favicon: https://minorplanetcenter.net/iau/figs/MPClogo16.png

  name: MPC Status
  introTitle: "Experimental prototype for automated real-time status for MPC servers and services"
  introMessage: "Users can follow issues automatically created in Github when downtime occurs"
  navbar:
    - title: GitHub Issues
      href: https://github.com/$OWNER/$REPO/issues
    - title: MPC Homepage
      href: https://minorplanetcenter.net
    - title: MPC Helpdesk
      href: https://mpc-service.atlassian.net/servicedesk/customer/portals
